### ISSUE TITLE
'dual_encoder_ranking' object has no attribute 'final_response_output'

### ISSUE THREAD

**Issue by priyanksonis** [jasonwu0731/ToD-BERT#10]
While evaluation on `response selection` with `batch_size < 100`, on this line:
[https://github.com/jasonwu0731/ToD-BERT/blob/master/models/dual_encoder_ranking.py#L95](https://github.com/jasonwu0731/ToD-BERT/blob/master/models/dual_encoder_ranking.py#L95)
we will get the error: `'dual_encoder_ranking' object has no attribute 'final_response_output'` , so please check this.

**Comment by jasonwu0731** [comment]
Updated it with args["eval_batch_size"] as shown [here](https://github.com/jasonwu0731/ToD-BERT/blob/master/models/dual_encoder_ranking.py#L95). Thanks.
