### ISSUE TITLE
Number of system acts for DSCT2 and GSIM

### ISSUE THREAD

**Issue by pawel-polyai** [jasonwu0731/ToD-BERT#11]
In the paper there are 19 system acts mentioned.
But when you query data you get 9 system acts?
`len(np.unique(data_info['sys_act']))`

The same applies to GSIM dataset.

**Comment by jasonwu0731** [comment]
Thanks for pointing this out, Pawel. We are going to double-check the universal-act mapping and will update the paper soon.
