### ISSUE TITLE
[Errno 2] No such file or directory: '/home/ToD-BERT-dev/data/MultiWOZ-2.1/train_dials.json'

### ISSUE THREAD

**Issue by zedavid** [jasonwu0731/ToD-BERT#12]
Hi, I'm trying to run the response generation code. I have downloaded the MultiWOZ data from [here](https://github.com/budzianowski/multiwoz), but I'm having some problems finding the mapping between the files the script is expecting and the ones I got from the MultiMOZ repo. Did you get the models from a different source?

Cheers!

**Comment by jasonwu0731** [comment]
Hi 

You can get the dataset from [here](https://drive.google.com/file/d/1EnGX0UF4KW6rVBKMF3fL-9Q2ZyFKNOIy/view?usp=sharing), which is preprocessed by this [file](https://github.com/jasonwu0731/trade-dst/blob/master/create_data.py)

**Comment by zedavid** [comment]
Hi! Thanks for sharing the processed data. I'm still having problems loading the data.

`Traceback (most recent call last):
  File "main.py", line 49, in <module>
    data_trn, data_dev, data_tst, data_meta = globals()["prepare_data_{}".format(ds_name)](args)
  File "/ToD-BERT-dev/utils/utils_multiwoz.py", line 183, in prepare_data_multiwoz
    update_ont_flag)
  File "/ToD-BERT-dev/utils/utils_multiwoz.py", line 95, in read_langs_turn
    data_detail["turn_usr_delex"] = turn["transcript_delex"].strip()
KeyError: 'transcript_delex`

It seems the script is expecting the delexicalised version of the data. Nor the data in the zip you shared or the data generated from the preprocessing script have this. Do you know how can I generate it?

Cheers!

**Comment by jasonwu0731** [comment]
are you sure you are using the correct data path? I download the zip file and open MultiWOZ-2.1/train_dials.json MultiWOZ-2.1/dev_dials.json MultiWOZ-2.1/test_dials.json, they do have the "transcript_delex" keys.

`{
                "transcript": "i would like a taxi from saint john s college to pizza hut fen ditton .",
                "system_transcript": "",
                "transcript_delex": "i would like a taxi from [attraction_name] to [restaurant_name] .",
                "system_transcript_delex": "",
                "turn_idx": 0,
                "belief_state": [
                    {
                        "slots": [
                            [
                                "taxi-destination",
                                "pizza hut fenditton"
                            ]
                        ]
                    },
                    {
                        "slots": [
                            [
                                "taxi-departure",
                                "saint johns college"
                            ]
                        ]
                    }
                ],
                "turn_label": [
                    [
                        "taxi-destination",
                        "pizza hut fenditton"
                    ],
                    [
                        "taxi-departure",
                        "saint johns college"
                    ]
                ],
                "system_acts": [],
                "domain": "taxi",
                "belief_state_vec": "[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]",
                "db_pointer": "[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0]"
            },
`
