### ISSUE TITLE
Input for DA classification: context and system turn

### ISSUE THREAD

**Issue by ItikaGupta** [jasonwu0731/ToD-BERT#13]
For DA classification, the input is in format:

dialogue history utterances from system and user [SYS] [SEP] system turn [USR] user turn

where we try to predict the DAs for the turn between [SEP] and [USR] token i.e. system turn.

I was wondering if you can explain why was the given format chosen? Specifically, 
why [SEP] after [SYS] token? and
why is there a following user turn after the system turn? 

I haven't found much information for DA prediction using BERT, and that's why any explanation will be very helpful.

BTW, I realized [here](https://github.com/jasonwu0731/ToD-BERT/issues/5#issuecomment-655763828) if sys_first_flag is outside, then system and user turns are actually system and user turns. But if it is inside (like before the code update), the system and user turn gets exchanged and in that case we end up predicting user utterance DAs given the above DA input format. (May be that's why the sys_first_flag was inside for loop before?) 

Thank you!

**Comment by jasonwu0731** [comment]
The reason why adding an [SEP] in the last dialogue turn is that we try to distinguish between context and the current utterances corresponding to the predicted action labels. For example, given (S1, U1, S2, U2, S3, U3), if we would like to predict dialogue act for turn 3, then the input will be (S1, U1, S2, U2, [SEP], S3, U3).

For the processing in this [line](https://github.com/jasonwu0731/ToD-BERT/blob/master/utils/dataloader_dm.py#L67), you can either do [SYS] [SEP] or [SEP] [SYS], it does not matter if you make it consistent during training and inference.

**Comment by ItikaGupta** [comment]
> why is there a following user turn after the system turn?

In the above example, the DA prediction is being made for S3 right? Then why do we give U3 as well? Wouldn't that be determined after S3's DA has been predicted in an online setting? Or was it assumed to be an offline setting?

Thank you so much!

**Comment by lulia0228** [comment]
I'm confused about the input for DA predict,。The history dialogue is (S1 U1 S2 U2), and we predict act in S3 。The S3 have not happened,  why S3 was added to input ?
