### ISSUE TITLE
How do I format new data for pertaining and fine-tuning tasks. 

### ISSUE THREAD

**Issue by shubham8111** [jasonwu0731/ToD-BERT#14]
I have my own dialogue dataset. I wanted to know in what format and structure should I put them to use during pre training along with other datasets.

**Comment by jasonwu0731** [comment]
you can follow any utility files under the utils folder, e.g., this [one](https://github.com/jasonwu0731/ToD-BERT/blob/master/utils/utils_msre2e.py)

**Comment by shubham8111** [comment]
Thanks.
