### ISSUE TITLE
Cannot reproduce the results in paper using your provided pre-trained models

### ISSUE THREAD

**Issue by YawYoung** [jasonwu0731/ToD-BERT#16]
Hi, @jasonwu0731 
I was finetuning the intent task using your provided [pre-trained models](https://github.com/jasonwu0731/ToD-BERT#pretrained-models)
But I got diffenent result which is shown below.
![image](https://user-images.githubusercontent.com/57999348/97516235-a7415980-19cd-11eb-9050-32004f2b64ea.png)

I used this [shell script](https://github.com/jasonwu0731/ToD-BERT/blob/master/evaluation_pipeline.sh#L11) and changed nothing.(Python3.6)

The second question is, according to your [code](https://github.com/jasonwu0731/ToD-BERT/blob/master/run_tod_lm_pretraining.sh#L11)
```
# ./run_tod_lm_pretraining.sh 0 bert bert-base-uncased save/pretrain/ToD-BERT-MLM --only_last_turn
# ./run_tod_lm_pretraining.sh 0 bert bert-base-uncased save/pretrain/ToD-BERT-JNT --only_last_turn --add_rs_loss
```
The model is pretrained with batchsize equal to 8 on one GPU. But in your paper, there were 2GPU and batchsize is 32.

**Comment by jasonwu0731** [comment]
Hi @YawYoung 

1. It seems that there are some variances between runs, can you do --nb_runs=3 (should be default using different random seeds) and check the results? Here are the results I got when I reran the intent experiments:
```
Average over 3 runs and 1 evals
acc: mean 0.8581212121212122 std 0.011117537168390397
ins_acc: mean 0.9507407407407408 std 0.0033766729837160048
oos_acc: mean 0.8948484848484849 std 0.009104636100952173
oos_recall: mean 0.4413333333333333 std 0.04616155206325811

Best Test Results: {'acc': 0.8732727272727273, 'ins_acc': 0.9551111111111111, 'oos_acc': 0.9070909090909091, 'oos_recall': 0.505}
```

2. For pre-training, I do not find much different while using two GPUs with bsz=16 each and one GPU with 8 samples. You can try yourself to see if there are any other better hyper-parameter settings.

**Comment by YawYoung** [comment]
Okk, thanks! ^-^
