### ISSUE TITLE
How to set dialog state tracking labels if the parts of histories are truncated

### ISSUE THREAD

**Issue by devjwsong** [jasonwu0731/ToD-BERT#19]
Hi, Thank you for this great repository and the paper.
I'm very impressed with your work.

I have a minor question.
How did you set the labels for dialog state tracking when the parts of dialog contexts are truncated?
If we set the maximum number of turns to certain number, then we should cut the precedent turns.
But if we do that, the dialog states which were updated in those turns should not appear in the ground truth labels since the model cannot see that slot types & values in the truncated dialog sequence.

For example, let us assume that the user wants to reserve a hotel room and specified the hotel name at the first turn.
Obviously, that name should be set as the value of slot type "hotel name" in dialog states.
But after the conversation goes on, the first turn will be cut out to make the input size shorter than the maximum size of the model, but the dialog state still has the hotel name as the updated value.
This looks unnatural for me since the model cannot see the context anymore but still has to predict the slot value as an output.

I wonder how you handled this problem.
Please let me know if there is an efficient preprocessing way to handle this.
Thank you.

**Comment by jasonwu0731** [comment]
Hi,

Yes, this is one of the limitations for the BERT-based model since the length of the max token is 512. In our work, we do not deal with states even if the dialogue is truncated.
