### ISSUE TITLE
Do you have the compiled data sets available to share?

### ISSUE THREAD

**Issue by songwangnlp** [jasonwu0731/ToD-BERT#2]
Hi, 

I am wondering whether you are able to share all the data sets you collected and compiled? It can be useful to when want want to test different models using the same data.

Thanks,
Song

**Comment by songwangnlp** [comment]
I think I may have the sources of the data here: http://nlpprogress.com/english/dialogue.html

**Comment by jasonwu0731** [comment]
happy to know that you figure it out.
