### ISSUE TITLE
Question about ToD-BERT as a pipeline

### ISSUE THREAD

**Issue by cabisarri** [jasonwu0731/ToD-BERT#22]
Hi Jason,

It is a very nice paper, and It helps enlighten me in a way to consider pre-training AE model for better downstream tasks. As a matte of fact, I am wondering how you plan to apply it to a complete pipeline (ToD bot). From what I see, those downstream tasks mentioned in the paper are actually sequential individual components inside the ToD bot. Here, I mean each task is related to the next task somehow, so fine-tuning on each separately seem to lose its connection property. I understand this fine-tuning wants to show its power due to such design or pre-training. Any thought? I appreciate it.

**Comment by jasonwu0731** [comment]
Hello, 

TOD-BERT was originally proposed as a pretrained LM that any TOD downstream task can be fine-tuned from. If you want to connect these components, I will suggest you check my other paper [simpleTOD](https://arxiv.org/abs/2005.00796) and its follow-up papers. Hope this help.
