### ISSUE TITLE
The download links of your pre-trained models are invalid now

### ISSUE THREAD

**Issue by smileix** [jasonwu0731/ToD-BERT#26]
the links are here:
https://drive.google.com/file/d/1vxqTda4MIYb1VDIA4NOokq7uCM4MW_1J/view?usp=sharing
https://drive.google.com/file/d/17F-wS4PwR6iz-Ubj0TaNsxNyMscgO3VV/view?usp=sharing
if possible, I hope you can update them. 
Thanks in advance.

**Comment by jasonwu0731** [comment]
Hi @smileix 

I linked them now to the huggingface.

* [ToD-BERT-mlm V1](https://huggingface.co/TODBERT/TOD-BERT-MLM-V1/tree/main)
* [ToD-BERT-jnt V1](https://huggingface.co/TODBERT/TOD-BERT-JNT-V1/tree/main)
