### ISSUE TITLE
Why are the user and system turns and labels switched in MWOZ and DSTC2 experiments? 

### ISSUE THREAD

**Issue by ItikaGupta** [jasonwu0731/ToD-BERT#5]
Based on the function read_langs_turn in utils_universal_act.py, the user and system turns are switched if the system is the first speaker. Why was this done?

**Comment by jasonwu0731** [comment]
Hi @ItikaGupta 

To make the format consistent, in the experiments we always start with system and then user. Thus, we just prefix an empty. system turn for datasets which are started by user.

Jason

**Comment by ItikaGupta** [comment]
Yes, for the datasets starting with user, it gets it right.

But for dataset such as dstc2, which starts with system turn; this code below from read_langs_turn function switches the user and system turn.

# Reading data
            for ti, turn in enumerate(dial_list):
                
                sys_first_flag = 1 if (ti==0 and turn["speaker"]=="[SYS]") else 0
                
                data_detail = get_input_example("turn")
                data_detail["ID"] = turn["conv_id"]
                data_detail["dialog_history"] = list(dialog_history)
                
                if sys_first_flag and ti % 2 == 1:
                    data_detail["turn_id"] = ti//2
                    data_detail["turn_usr"] = turn["raw_text"].strip()
                    data_detail["turn_sys"] = dial_list[ti-1]["raw_text"].strip()
                    data_detail["sys_act"] = dial_list[ti-1]["label"]
                    data.append(data_detail)
                    dialog_history.append(data_detail["turn_sys"])
                    dialog_history.append(data_detail["turn_usr"])

                elif not sys_first_flag and ti % 2 == 0:
                    data_detail["turn_id"] = (ti+1)//2
                    data_detail["turn_usr"] = turn["raw_text"].strip()
                    data_detail["turn_sys"] = dial_list[ti-1]["raw_text"].strip() if ti > 0 else ""
                    data_detail["sys_act"] = dial_list[ti-1]["label"] if ti > 0 else []
                    data.append(data_detail)
                    dialog_history.append(data_detail["turn_sys"])
                    dialog_history.append(data_detail["turn_usr"])

**Comment by jasonwu0731** [comment]
The sys_first_flag needs to be in front of the for loop. Update [here](https://github.com/jasonwu0731/ToD-BERT/blob/master/utils/utils_universal_act.py#L22). Thanks for letting me know.
