### ISSUE TITLE
Mapping response selection output

### ISSUE THREAD

**Issue by ItikaGupta** [jasonwu0731/ToD-BERT#7]
Hi Jason,

The response selection output gives an array of 100 elements, that I believe are ranked from top 1 to top 100 (where one of them is a true response and the other 99 are the responses in the same batch for other inputs - treated as negative samples).

I was wondering how do I map these indices to the actual responses? As in what part of the code is mapping the responses to these indices? I see there is code in the dataloader_nlg.py file, however I also noticed that the code below never gets executed as the nb_neg_sample_rs is 0. Could you please guide how do I interpret the test output? 

Thanks in advance!

 
       if self.args["nb_neg_sample_rs"] != 0 and self.mode == "train":
            if self.args["sample_negative_by_kmeans"]:
                try:
                    cur_cluster = self.others["ToD_BERT_SYS_UTTR_KMEANS"][self.data["turn_sys"][index]]
                    candidates = self.others["KMEANS_to_SENTS"][cur_cluster]
                    nb_selected = min(self.args["nb_neg_sample_rs"], len(candidates))
                    try:
                        start_pos = random.randint(0, len(candidates)-nb_selected-1)
                    except:
                        start_pos = 0
                    sampled_neg_resps = candidates[start_pos:start_pos+nb_selected]
                
                except:
                    start_pos = random.randint(0, len(self.resp_cand_trn)-self.args["nb_neg_sample_rs"]-1)
                    sampled_neg_resps = self.resp_cand_trn[start_pos:start_pos+self.args["nb_neg_sample_rs"]]  
            else:
                start_pos = random.randint(0, len(self.resp_cand_trn)-self.args["nb_neg_sample_rs"]-1)
                sampled_neg_resps = self.resp_cand_trn[start_pos:start_pos+self.args["nb_neg_sample_rs"]]
            
            neg_resp_arr, neg_resp_idx_arr = [], []
            for neg_resp in sampled_neg_resps:
                neg_resp_plain = "{} ".format(self.sys_token) + neg_resp
                neg_resp_idx = self.preprocess(neg_resp_plain)[:self.max_sys_resp_len]
                neg_resp_idx_arr.append(neg_resp_idx)
                neg_resp_arr.append(neg_resp_plain)
            
            item_info["neg_resp_idx_arr"] = neg_resp_idx_arr
            item_info["neg_resp_arr"] = neg_resp_arr

**Comment by jasonwu0731** [comment]
Hi @ItikaGupta 

Negative responses are other responses in the same batch, so you can just check data["response_plain"][bsz_index] to get those plain text.

For the code you are showing, yes it is not used in the current setting. What I found in the experiments is, how to select negative responses is important, and in that part I tried to first conduct clustering before sampling. Similar observation is also found in this [paper](https://arxiv.org/pdf/2004.04906.pdf) published recently. You can check their Table 4.

Let me know if you have any further questions or ideas.
