### ISSUE TITLE
Use ToD-BERT for response selection

### ISSUE THREAD

**Issue by priyanksonis** [jasonwu0731/ToD-BERT#8]
@jasonwu0731 

How can we use this model for downstream task of "response selection" after loading model from HF ?, than how to do finetuning on our own dataset?

**Comment by jasonwu0731** [comment]
Hi @priyanksonis 

To run experiments for response selection, you can check [here](https://github.com/jasonwu0731/ToD-BERT/blob/master/evaluation_pipeline.sh#L94)
